### ISSUE TITLE
Add Support in Readme.md

### ISSUE THREAD

**Issue by obitodarky** [MozillaIndia/mozillaindia.github.io#113]
Should we add support information in readme.md so that people can propose and discuss new ideas there instead of randomly sending PRs on the repo?

![Screenshot 2019-04-17 at 8 06 58 AM](https://user-images.githubusercontent.com/21317964/56256911-36d33000-60e8-11e9-83db-84bcb2206c2d.png)

**Comment by asdofindia** [comment]
CONTRIBUTING.md is supposed to do exactly that and there is a mention of it in README.md

Ideally discussions about the repository should be in the repository itself and not on telegram

**Comment by obitodarky** [comment]
Okay, great. I think you can close this issue now. I was thinking if they wanted to ask something about Mozilla India or something related there should be a link so that they can contact us.

**Comment by asdofindia** [comment]
The entire mozillaindia.org website is full of those links. Repeating them would be counter-productive.
