### ISSUE TITLE
Community profile improvement

### ISSUE THREAD

**Issue by obitodarky** [MozillaIndia/mozillaindia.github.io#116]
Should we add license and code of conduct to the repo? 
I think it's a good idea. We should at least add the license since we are already using MPL and CC licenses.  

![Screenshot 2019-04-21 at 11 07 34 AM](https://user-images.githubusercontent.com/21317964/56465889-c26cf980-6425-11e9-9b1a-aece68c443f9.png)

**Comment by asdofindia** [comment]
Yes. Good idea.
Code of conduct can point to Mozilla's community participation guidelines.
