### ISSUE TITLE
Accessibility Improvement

### ISSUE THREAD

**Issue by harshil1712** [MozillaIndia/mozillaindia.github.io#132]
I ran a lighthouse test to check the accessibility of the website and found the score as below.
![Screenshot from 2019-06-07 17-48-23](https://user-images.githubusercontent.com/18901032/59103469-8c8bc200-894c-11e9-887d-ebab5a5a9d4d.png)
On running the test a lot of suggestions were given which can help us to improve the score and make the website more accessible. Below are the lists of the changes we can make.
- [ ] "We’re building a better Internet" This section has issue with color contrast. Low-contrast text is difficult or impossible for many users to read
- [ ] <html> element doesn't have the [lang] attribute
- [ ] The <img> elements doesn't have [alt] attributes.

These small changes can help us make the website more accessible.

I would like to work on this issue, and would like to discuss more about it.

**Comment by obitodarky** [comment]
Hey, thanks for bringing this up. Can you tell us how'd you check the accessibility and what tool you used? I just ran it on [web.dev](web.dev) and it gave and accessibility score of 87.  

- I also believe the contrast is a bit low. However I haven't had any problem reading it on a monitor or on a mobile.
As for the issue. Just drop a PR and feel free to contribute!

**Comment by harshil1712** [comment]
@obitodarky I ran the [lighthouse](https://developers.google.com/web/tools/lighthouse/) test on the chrome dev tools. 

>     * I also believe the contrast is a bit low. However I haven't had any problem reading it on a monitor or on a mobile.

The goal here is to make it accessible for all. Sure both you and me can read it easily, without difficulty, but it becomes difficult for the people with weak eye sight. 
I will soon do a PR with the changes!

**Comment by obitodarky** [comment]
> The goal here is to make it accessible for all. Sure both you and me can read it easily, without difficulty, but it becomes difficult for the people with weak eye sight.
> I will soon do a PR with the changes!
If you're on it. I also ran it on Mozilla's Dev Tool 
![Screenshot 2019-06-07 at 6 35 48 PM](https://user-images.githubusercontent.com/21317964/59106277-a1b81f00-8953-11e9-83a0-197cbf4203b1.png)

Seems like the links in the footer **might** be having contrast issues. If you have any suggestions on those. You can go ahead

**Comment by asdofindia** [comment]
Accessibility is a core value of Mozilla. Thanks for the work. I'll be happy to be of help in merging fixes promptly and also in helping choose frameworks/tools to improve accessibility if needed.

The "lang" bit reminds me that we also need to have translations into various indian languages, but perhaps that can be tracked in a different issue.

**Comment by harshil1712** [comment]
@asdofindia @obitodarky I made some changes locally and got the following result
![Screenshot from 2019-06-07 19-25-23](https://user-images.githubusercontent.com/18901032/59110011-c912ea00-895b-11e9-9489-cb6848f8776e.png)

Still there are issues with the color contrast. I am not sure how to tackle those.
I am sending a PR with the changes I've made.

**Comment by obitodarky** [comment]
> @asdofindia @obitodarky I made some changes locally and got the following result

Good work and thanks for the changes
> Still there are issues with the color contrast. I am not sure how to tackle those.

I think the issue is in the color of the `notification, is-success` attributes. I tested it out I changed the background color to `#2382d1` and the font to bold(changing attribute to `title` from `subtitle` also seems to work). I think I got it cleared. Still, can you double check if it's ok in your test @harshil1712?

**Comment by harshil1712** [comment]
I tested it by changing the class `is-success` to `is-link` and it solved the issue, there was no need to add the `title` class. But by changing the class the background color changes, and this was what I was unsure about. 
Earlier
![Screenshot from 2019-06-07 20-14-59](https://user-images.githubusercontent.com/18901032/59112613-fb731600-8960-11e9-9bda-40b458144ca6.png)
After changing the class:
![Screenshot from 2019-06-07 20-14-34](https://user-images.githubusercontent.com/18901032/59112620-02018d80-8961-11e9-85e4-f83b739b1e1f.png)
If there is no issue with changing the color, this works pretty good.

**Comment by asdofindia** [comment]
The colour chosen is more or less random. So, another random colour doesn't make a difference.

Maybe there are designers here who may have a comment on colour tones.

**Comment by obitodarky** [comment]
I think this can be added since it solves the issue. Changes in color can later be added if someone has a better idea.

**Comment by harshil1712** [comment]
Okay so I will push those changes too. But we still need to find a solution for color contrast in the footer.

**Comment by obitodarky** [comment]
It looks fine to me.
