### ISSUE TITLE
Horizontally Arrange Groups

### ISSUE THREAD

**Issue by harshil1712** [MozillaIndia/mozillaindia.github.io#136]
The website currently has vertically aligned the groups. Since these groups vary in number, some blocks are longer than the other. This makes the site unsymmetrical, and it doesn't look good. A solution to this to have them arranged horizontally. We can even use a carousel to implement this.

**Comment by obitodarky** [comment]
I agree. A carousel would look nice. However, I would suggest that it be implemented in pure CSS since we are keeping the repo simple for new contributors(correct me if I'm wrong)

**Comment by asdofindia** [comment]
Absolutely agree that it looks ugly.
I would prefer a solution that leaves all the items visible on the screen at all the time. Reasons are:
1. Visibility for everyone
2. Ctrl+F works
3. Many other thoughts come to mind

Perhaps, we can have all the regional groups come first (arranged horizontally with wrap after 3 columns); then functional groups in the same way; and then campus clubs in the same way.

**Comment by Amorpheuz** [comment]
![image](https://user-images.githubusercontent.com/22113778/59443453-a2502a00-8e19-11e9-9621-51d9168f5044.png)
Will something like this work? done using flexbox....

**Comment by asdofindia** [comment]
That looks great @Amorpheuz, Bulma framework has good support of flex box and there probably is a way to achieve this without writing any custom css. Please take a look at https://bulma.io/documentation/layout/tiles/

**Comment by Amorpheuz** [comment]
![image](https://user-images.githubusercontent.com/22113778/59452878-5195fc80-8e2c-11e9-8655-579b1ad2b56e.png)

Here's an implementation using Tiles utilities, the only drawback I see to this is that there is no wrapping functionality inbuilt into these, so one will have to manually declare every row(tile is-ancestor) after X (in my case 3) elements.
