### ISSUE TITLE
Horizontal Scroll on Site

### ISSUE THREAD

**Issue by Amorpheuz** [MozillaIndia/mozillaindia.github.io#138]
While I was working on arranging the groups on the site, I found that the website gets a bit of Horizontal scroll on resolutions with width less than that of 1440p all the way to mobile. From looking around a bit in chrome developer tools, I found it's from how the tile system is used to arrange the boxes.
![image](https://user-images.githubusercontent.com/22113778/59514734-16063b80-8edb-11e9-8292-6377ed8cee8f.png)

It can be fixed be either fixed by disabling _overflow-x_ or In my opinion, the better way, _re-structuring how tiles are used_. I can do it over the weekend if people are up for it. Can assure that the website will look the same albeit the boxes might increase/decrease in size by a few pixels.

**Comment by asdofindia** [comment]
Kindly go ahead keeping #136 also in mind
