### ISSUE TITLE
Spacing issue in groups

### ISSUE THREAD

**Issue by obitodarky** [MozillaIndia/mozillaindia.github.io#147]
## Bug
Alignment/Spacing isn't fixed in horizontal containers.

**Actual Behaviour**
Spaces in some group links in containers aren't aligned properly. Adding a line doesn't seem to fix the problem. The containers behave differently for different resolutions. See #144 

**Expected Behaviour**

All links should be properly aligned
![Screenshot 2019-07-01 at 7 38 37 PM](https://user-images.githubusercontent.com/21317964/60588304-39bef200-9db4-11e9-8115-521d8779d4a4.png)

**Screenshots of the issue**

![Screenshot 2019-06-20 at 11 29 04 AM](https://user-images.githubusercontent.com/21317964/60588329-4e9b8580-9db4-11e9-9611-51132bdeaa13.png)

**Would you like to work on the issue?**
No. But I believe @Amorpheuz  or @harshil1712  can do something about this.

**Comment by harshil1712** [comment]
How does this look?

![Screenshot from 2019-07-03 18-51-03](https://user-images.githubusercontent.com/18901032/60594963-b6a59800-9dc3-11e9-9e1d-84226e191207.png)

**Comment by obitodarky** [comment]
I'm not so sure about this. Maybe we can fix this in the new framework instead (If we are quickly going ahead with it)

**Comment by harshil1712** [comment]
I have committed my changes. Let me know if I should do the PR

**Comment by asdofindia** [comment]
It kind of works. But also the css selector may have to be slightly more specific to avoid collision with other `.subtitle`s.

I think, like Harsh says, this may automatically be solved in the process of switching framework.

**Comment by soulspark666** [comment]
I think the Alignment/Spacing problem is because of the unresponsiveness of the site. As you can see in the images below
![1](https://user-images.githubusercontent.com/37495396/60751769-2c1f8d00-9fab-11e9-8126-5869fd2d8ac9.png)
![2](https://user-images.githubusercontent.com/37495396/60751771-2cb82380-9fab-11e9-8918-79f45e2fcc48.png)
![3](https://user-images.githubusercontent.com/37495396/60751772-2cb82380-9fab-11e9-8061-d982ab3f5a9d.png)

**Comment by harshil1712** [comment]
Hey @obitodarky, unfortunately this issue didn't get solved. May you please open it and add Hacktoberfest label? 
Thanks.

**Comment by asdofindia** [comment]
What do you say we drop Bulma altogether and switch to pure css? I think grid and flexbox can solve most issues.

**Comment by obitodarky** [comment]
@harshil1712 can you show me how it works on your device? I checked on my device with different resolutions, it seems to be working just fine.

**Comment by harshil1712** [comment]
@asdofindia removing a whole CSS framework would sure solve one or two issues, but this will definitely create a whole lot of new issues. The major issue, I feel will be with responsiveness. The website will be broken, and writing CSS for scratch to make the website responsive, will take up a lot of time.

**Comment by harshil1712** [comment]
> **Expected Behaviour**
> 
> All links should be properly aligned
> ![Screenshot 2019-07-01 at 7 38 37 PM](https://user-images.githubusercontent.com/21317964/60588304-39bef200-9db4-11e9-8115-521d8779d4a4.png)
> 
> **Screenshots of the issue**
> 
> ![Screenshot 2019-06-20 at 11 29 04 AM](https://user-images.githubusercontent.com/21317964/60588329-4e9b8580-9db4-11e9-9611-51132bdeaa13.png)
> 


Hey @obitodarky, it looks the similar like the screenshots you have shared. The boxes are not of the same height.
