### ISSUE TITLE
Update the README.md

### ISSUE THREAD

**Issue by harshil1712** [MozillaIndia/mozillaindia.github.io#151]
## Enhancement
The README.md file needs to be updated for the `gatsby` branch.

**Comment by harshil1712** [comment]
@obitodarky are you working on this?

**Comment by obitodarky** [comment]
Yes. I'll start working on this ASAP.

**Comment by arps18** [comment]
I would like to work on it. Can u provide me with the requirements!

**Comment by harshil1712** [comment]
@arps18 there's already a PR by @obitodarky.

**Comment by asdofindia** [comment]
@arps18, perhaps you can work on #157 ? Closing this one.
