### ISSUE TITLE
Add CONTRIBUTE.md and Update License in gatsby branch

### ISSUE THREAD

**Issue by harshil1712** [MozillaIndia/mozillaindia.github.io#152]
## Bug/Feature/Enhancement
There is currently no contributing doc for the Gatsby website. Also the License has to be changed.

**Would you like to work on the issue?**
If someone wants to take it feel free, or I'll be happy to take this.

**Comment by asdofindia** [comment]
#157 tracks the docker situation in CONTRIBUTING.md
