### ISSUE TITLE
Need to either remove/update docker setup instructions

### ISSUE THREAD

**Issue by asdofindia** [MozillaIndia/mozillaindia.github.io#157]
CONTRIBUTING.md still mentions docker which was added by @kmehant in #142 (based on #141 )

We have to either update the instructions + setup docker-compose on the gatsby branch OR remove it altogether.

**Comment by kmehant** [comment]
@asdofindia I can assist you in updating the docker configurations for Gatsby site. What are your it thoughts?

**Comment by asdofindia** [comment]
@kmehant, as [I said previously](https://github.com/MozillaIndia/mozillaindia.github.io/pull/142#issuecomment-506219799), I don't use docker neither find value in it. But, if you are maintaining it, no issue in keeping it.

**Comment by kmehant** [comment]
@asdofindia, I agree with you, I wasn't sure about the deployment flow of this static site. Docker would be a great use to create isolated deployments on either development or production servers. However, as this is a simple project, it would be fine to remove docker layers to this project.

**Comment by asdofindia** [comment]
Okay. I second removing all docker related stuff from the code.

Things to do, I think:
- [ ] remove .dockerignore
- [ ] remove reference to docker in the CONTRIBUTING.md file
