### ISSUE TITLE
Improve data structure in campusclubs.json file

### ISSUE THREAD

**Issue by harshil1712** [MozillaIndia/mozillaindia.github.io#160]
## Enhancement

**Actual Behaviour**

The campusclubs.json file doesn't follow a proper structure. Different objects contain different fields. 

**Expected Behaviour**

Create a proper data structure for camousclubs.json file. 

**Screenshots of the issue**

**Would you like to work on the issue?**

This is issue open for anyone who is interested in contributing!

**Comment by yushiiii** [comment]
Would like to work on this issue
