### ISSUE TITLE
Change GitHub to github in data files

### ISSUE THREAD

**Issue by harshil1712** [MozillaIndia/mozillaindia.github.io#161]
## Enhancement

**Actual Behaviour**

The data files have key name "GitHub". 

**Expected Behaviour**

The key name should be changed to github (following best practices) 

**Screenshots of the issue**

**Would you like to work on the issue?**

This is issue open for anyone who is interested in contributing!

**Comment by wpalacios** [comment]
@harshil1712 I would like to work on this issue

**Comment by obitodarky** [comment]
@wpalacios please feel free to work on this issue. But also look out for any [Open Pull Requests](https://github.com/MozillaIndia/mozillaindia.github.io/pulls?q=is%3Aopen+is%3Apr) that may be solving this issue so that you don't waste your time.

**Comment by cseas** [comment]
Hasn't this been fixed by #170 ?
Is something still left to be done?

**Comment by asdofindia** [comment]
You're right. This has been fixed by #170. Thanks everyone who pitched in.
