### ISSUE TITLE
Use icons instead of texts

### ISSUE THREAD

**Issue by harshil1712** [MozillaIndia/mozillaindia.github.io#162]
## Enhancement

**Actual Behaviour**

Currently the links to social media platforms are text, which doesn't look good. Makes the site look mundane.

**Expected Behaviour**

Use of icons instead of text.

**Would you like to work on the issue?**

This issue is open for anyone who is interested in contributing!

**Comment by Lawrence4code** [comment]
I'd like to work on this task, please confirm.

**Comment by mazsam** [comment]
@harshil1712  Could you assign this one to me ?

**Comment by harshil1712** [comment]
Hey @Lawrence4code sure. @mazsam maybe you folks can work together and help us close this issue :smile:

**Comment by nik72619c** [comment]
there are icons followed by texts, do you want only the icons in this case shown in a horizontal manner ?

**Comment by nik72619c** [comment]
@harshil1712 please guide me on this !

**Comment by harshil1712** [comment]
Hey @nik72619c sorry for the late reply. We would like to have only the icons, and not the text.

**Comment by nik72619c** [comment]
Okay , will file a PR on this !

**Comment by nik72619c** [comment]
Do you wish to see  the icons list horizontally or vertically ?

**Comment by harshil1712** [comment]
Hey, @nik72619c what do you think, what will look good? I guess horizontal list would look good. But we are open to new ideas!

**Comment by nik72619c** [comment]
I also think that horizontal lists would look good

**Comment by nik72619c** [comment]
ref #183 :)

**Comment by AnkitaAditya20** [comment]
i am working on this issue

**Comment by abhishek-pes** [comment]
iam working on this issue
