### ISSUE TITLE
Invalid value used in size prop for react-icons

### ISSUE THREAD

**Issue by Amorpheuz** [MozillaIndia/mozillaindia.github.io#165]
## Bug

**Actual Behaviour**

The size prop has been used incorrectly here. fa-2x should be passed as a class to scale font-awesome icons. The size prop substitutes the height and width attributes of the svg, as shown here:
```
<svg stroke="currentColor" fill="currentColor" stroke-width="0" viewBox="0 0 448 512" color="#1da1f2" style="color:#1da1f2" height="fa-2x" width="fa-2x" xmlns="http://www.w3.org/2000/svg">...</svg>
```
The react-icons uses svg and not font-awesome, so I doubt passing fa-2x as a class might work either, would have to check that out.

**Expected Behaviour**

Correct value to be passed to `Size` prop that is compatible with `Height` and `Width` attributes of an svg element.

**Screenshots of the issue**

Leads to console errors.
![image](https://user-images.githubusercontent.com/22113778/65819905-cc4e2080-e23f-11e9-8107-2cd24141f415.png)

**Would you like to work on the issue?**

Anyone is free to resolve this issue.

**Comment by Lawrence4code** [comment]
I'd like to work on it please.

**Comment by Amorpheuz** [comment]
Sure @Lawrence4code , go ahead!
