### ISSUE TITLE
Missing / Invalid path to bg-sand.png

### ISSUE THREAD

**Issue by Amorpheuz** [MozillaIndia/mozillaindia.github.io#166]
## Bug

**Actual Behaviour**

Missing / Invalid path to `bg-sand.png`.
https://github.com/MozillaIndia/mozillaindia.github.io/blob/329345ccf86b3c14cdc4d62fc0bdb7853b8bcb99/src/components/layout.css#L3
Was the file lost during transition? Or incorrectly named instead of the gradient file.

**Expected Behaviour**

Locate the actual file if present in earlier version or remove it.

**Screenshots of the issue**

Leads to console error:
![image](https://user-images.githubusercontent.com/22113778/65820043-ff91af00-e241-11e9-81c5-efd21f9cfbe4.png)

**Would you like to work on the issue?**

In case the file was incorrectly named, anyone is free to fix it ensuring site's look and feel don't change.

**Comment by wpalacios** [comment]
@obitodarky I would like to work on this.

**Comment by sohaibalam67** [comment]
The file `bg-sand.png` is not present in this repository.
should `url("/img/bg-sand.png") repeat` be removed from the background stack or the file wasn't committed?

**Comment by Amorpheuz** [comment]
Fixed with #168, thanks!
