### ISSUE TITLE
Clean indentation, set up style guide

### ISSUE THREAD

**Issue by asdofindia** [MozillaIndia/mozillaindia.github.io#173]
## Enhancement

There is an editorconfig file but I don't think all the source files in the repository have consistent indentation, etc. It will be good to have that consistency for the sake of making contributions easy and clean. (See: #172)

**Comment by In4No** [comment]
> ## Enhancement
> There is an editorconfig file but I don't think all the source files in the repository have consistent indentation, etc. It will be good to have that consistency for the sake of making contributions easy and clean. (See: #172)

I can pick this up. Just one question. Should I raise one pull request per file? As it will be easier to review.

**Comment by asdofindia** [comment]
You can change all the files simultaneously in one commit as long as all that is being done is formatting.

But we can also first discuss what needs to be the canonical style everyone sticks to. I think 2 space indent is okay for all files. That's just me. I don't mind 4 spaces either.

**Comment by In4No** [comment]
Two space indent and max line length of 100 chars? It makes the code readable even when not using zen mode.

**Comment by Amorpheuz** [comment]
I think getting `eslint` setup for this would be a good idea! We could have set up `.eslint.rc.*` file for the same and require contributors to run it for PRs. We can also set up prettier / eslint pre-push hooks that would ensure standardized pushes irrespective of contributor styling. What do you think about this @harshil1712 ?  I did notice the `.prettierrc` in code but would recommend integrating eslint with it too! They do have a guide for the same [Integrating Prettier with Linters](https://prettier.io/docs/en/integrating-with-linters.html).

**Comment by In4No** [comment]
eslint makes sense

**Comment by harshil1712** [comment]
I agree with @Amorpheuz. @In4No can you set up eslint instead? This will reduce the manual labor, and will help to maintain the structure in the future as well.

**Comment by In4No** [comment]
Ya. Will do that.

**Comment by In4No** [comment]
Raised a PR. I had to disable a bunch of rules, and had to fix the files, else, eslint was throwing error.
