### ISSUE TITLE
Blog: Log in button leads to Callback URL mismatch

### ISSUE THREAD

**Issue by cseas** [MozillaIndia/mozillaindia.github.io#180]
## Bug/Feature/Enhancement
Bug

**Actual Behaviour**
`Log in` link under `Meta` in `Explore` sidebar leads to error page:
```
Callback URL mismatch.
The provided redirect_uri is not in the list of allowed callback URLs.
```

**Expected Behaviour**
Perhaps a way to log in to the site, or a message mentioning some contact details to get in touch with the maintainers.

**Screenshots of the issue**
![Selection_051](https://user-images.githubusercontent.com/29686866/66343979-6150c800-e96a-11e9-841a-4815bc9669db.png)

**Would you like to work on the issue?**
I'd love to, but I'm not sure of the reason behind this issue.

**Comment by asdofindia** [comment]
This was occurring because MCWS moved to Auth0 based SSO and the login.php link wasn't being redirected correctly. Have fixed this.

**Comment by asdofindia** [comment]
Sorry wrongly referenced in an unrelated commit. And then wrongly reopened. Now going to rightly close this again.
