### ISSUE TITLE
No 404 page.

### ISSUE THREAD

**Issue by kkdeep** [MozillaIndia/mozillaindia.github.io#35]
It seems that there is no 404 page included in the source.Tried with random url's but instead of returning a dedicated 404 page it returns normal 404 error along with server info
"Apache/2.2.22 (Ubuntu) Server at mozillaindia.org Port 80" :smiley:

**Comment by yash14123** [comment]
I will take this up

**Comment by sudheesh001** [comment]
@yash14123 Sure, please go ahead, we're looking towards a patch.

**Comment by Chandan-Baba** [comment]
Hello team,
I have added a pull request for this, please take a look.
