### ISSUE TITLE
Automate deployment

### ISSUE THREAD

**Issue by asdofindia** [MozillaIndia/mozillaindia.github.io#72]
Currently, it looks like, the server needs to be manually updated with the latest code every time a commit is made. It'd be a wise idea to automate this step (using a webhook maybe)

If there's a concern about breaking the site unintentionally, we could use master branch to stay in automatic sync with server and gh-pages shall act like a dev branch. Such that automatic deployment happens only when changes are merged from gh-pages to master.  
## 

If we're automating, I'd go for a simple php script that pulls changes, considering our server is apache.

**Comment by nileshgulia1** [comment]
Hello @asdofindia , What's the update regarding this issue?

**Comment by asdofindia** [comment]
I think this has been fixed with [the migration to participation infrastructure] (https://discourse.mozilla.org/t/migration-of-mozilla-india-blog-and-website-to-participation-infrastructure/19152?u=asdofindia) as the site is now directly served from GitHub
