### ISSUE TITLE
404 not found 

### ISSUE THREAD

**Issue by nileshgulia1** [MozillaIndia/mozillaindia.github.io#86]
On opening mozillaindia.org it says 404 not found always
![screenshot from 2017-09-05 01-51-28](https://user-images.githubusercontent.com/22280901/30037854-afc14c9a-91dc-11e7-8367-68f3fb906e1a.png)

**Comment by asdofindia** [comment]
Thanks for reporting. This should get fixed in a couple of hours, probably.

**Comment by asdofindia** [comment]
It took a bit longer, but [fixed](https://discourse.mozilla.org/t/migration-of-mozilla-india-blog-and-website-to-participation-infrastructure/19152)!

**Comment by nileshgulia1** [comment]
Great!1!!!
