### ISSUE TITLE
[Updating] Links and necessary points

### ISSUE THREAD

**Issue by greed2411** [MozillaIndia/mozillaindia.github.io#89]
Your twitter handle @MozillaIN goes to [old page](https://mozillaindia.org/) which isn't responsive and looks like this 
![screenshot-2017-11-17 mozilla india](https://user-images.githubusercontent.com/21098186/32932176-8426919a-cb8d-11e7-8cce-879338b3e91a.png)
instead of the [new one](http://mozillaindia.github.io/)

yes did use the firefox quantum dev edition (58.b4) . Cool work with the screenshot.

I did go through [Migration of Mozilla India Blog and Website to Participation Infrastructure](https://discourse.mozilla.org/t/migration-of-mozilla-india-blog-and-website-to-participation-infrastructure/19152) which talked about the migration to the new site and security issues.

One more, new website isn't talking about firefox quantum, also the links to Firefox for Desktop and Firefox for Android still redirect to the old versions.

And as the guide says, the leaderboard redirects to the old website.
Have created an issue, im not sure whether it followed contributing guidelines. thought i might drop by and inform this.

**Comment by greed2411** [comment]
Pull request has been made, [here](https://github.com/MozillaIndia/mozillaindia.github.io/pull/90)

**Comment by asdofindia** [comment]
This is no longer relevant I think. Thanks for the issue. Feel free to re-open if it is still relevant.
