### ISSUE TITLE
Blog activities redesign

### ISSUE THREAD

**Issue by obitodarky** [MozillaIndia/mozillaindia.github.io#96]
I don't think the front page of the Blog needs to be that long. We could use small panels maybe. Instead of showing the activities vertically, we can do it horizontally.
And of course, it would be a small preview of the activity

Like so.
![Screenshot 2019-04-15 at 10 51 46 PM](https://user-images.githubusercontent.com/21317964/56152483-6a6f6680-5fd1-11e9-9d8b-d8d50b3036b9.png)

**Comment by asdofindia** [comment]
Can you do this if granted access? If yes, please share your email ID to be added

**Comment by obitodarky** [comment]
@asdofindia I can definitely try. I'll clone the site on my localhost and try making changes there, if successful, we can proceed further.

**Comment by asdofindia** [comment]
Perfect. That is the approach I took when I [made my first bug fix on mozilla india blog](https://blog.learnlearn.in/2015/09/did-i-screw-up-mozilla-india-blogs.html)

But for this particular problem you pointed out, I think the fix should happen at a theme level. In fact, I just logged in to the themes section and saw these themes are available:
![image](https://user-images.githubusercontent.com/945777/56190262-73028400-6047-11e9-84fc-e6c9eabc247c.png)

Perhaps it is better to switch to a more modern theme like frontierline which comes with this built-in?

**Comment by obitodarky** [comment]
I agree, we should definitely switch to a modern theme. We could also add new plugins for better visuals. 
Can you add my email address? I can DM on Telegram.

**Comment by asdofindia** [comment]
Yes

**Comment by obitodarky** [comment]
To whoever did the redesign, good work! 
I'm closing this issue now.

**Comment by asdofindia** [comment]
I had changed the theme to modern. Forgot to document.
