### ISSUE TITLE
Include link to activate mozilla community

### ISSUE THREAD

**Issue by asdofindia** [MozillaIndia/mozillaindia.github.io#97]
https://activate.mozilla.community/

Suggested by [Lucy](https://discourse.mozilla.org/t/mozilla-india-website-needs-you/38300/2?u=asdofindia)

**Comment by thetronjohnson** [comment]
@asdofindia I think this issue can be closed

**Comment by asdofindia** [comment]
It has been added to the navbar, but also needs to be added to the text near the contribute wiki. The navbar isn't visible without additional interaction on mobile and therefore isn't the ideal place for activate link. Also people who are clueless about how to contribute should be given a context in the form of sentence. For example, text like "find impactful and easy ways to contribute to mozilla in the activate mozilla community website"

**Comment by obitodarky** [comment]
I think this can be closed now.
