### ISSUE TITLE
Include link to contribute wiki

### ISSUE THREAD

**Issue by asdofindia** [MozillaIndia/mozillaindia.github.io#98]
https://wiki.mozilla.org/Contribute

Suggested by [Lucy](https://discourse.mozilla.org/t/mozilla-india-website-needs-you/38300/2?u=asdofindia)

**Comment by obitodarky** [comment]
please check out https://github.com/MozillaIndia/mozillaindia.github.io/pull/105

**Comment by asdofindia** [comment]
Fixed in #105
